version: "2.3"
services:
  game_websocket_app:
    command: /bin/bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    build:
      context: ./game_websocket_app/docker
    volumes:
      - ./game_websocket_app/:/app
    working_dir: /
    container_name: game_websocket_app
    ports:
      - "80:80"
